import type { Metadata } from "next";
import { Roboto, Inter,JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({
  subsets: ["latin"],
});

const jetBrains = JetBrains_Mono({
  subsets:['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(jetBrains.className)}>
        <div className="relative px-6 antialiased text-base sm:px-10 overflow-hidden">
          {children}
        </div>
      </body>
    </html>
  );
}
