import type { Metadata } from "next";
import { Chivo_Mono as Chivo } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const chivo = Chivo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(chivo.className)}>
        <div className="container relative px-6 overflow-hidden">{children}</div>
      </body>
    </html>
  );
}
